### ISSUE TITLE
[question]: Very good library, ask a few questions

### ISSUE THREAD

**Issue by WeiKuang** [JDongKhan/flutter_chart#1]
1. How to color the area between lines?
2. How to use the shaders in the line, can you give an example?
3. How to display different colors when greater than or less than the specified value?
thank you

**Comment by JDongKhan** [comment]
不好意思，最近在忙。 
1、我在line里面增的加了operation属性。
2、我在example里面增加了对 shaders的使用demo。
3、目前无法实现该功能，这种要嘛将点拆的足够细，要嘛需要给整个控件增加一个过渡色。

**Comment by WeiKuang** [comment]
@JDongKhan 
作者，你好。
很高兴听到你的回复。在使用这个库的过程中，遇到了几个问题，想请教您一下。
1、假设共有1440个点（1天数据，1分钟一个），x轴坐标只显示24个值，也就是几点钟。
在不需要横向滚动的前提下，如何设置x轴？
我是这样设置的
```dart
  xAxis: XAxis(
    count: 24,
    max: 1440,
    interval: 60,
    formatter: (index) {
      int num = index.toInt();
      if (num.isOdd) {
        return "";
      }
      return index.toString();
    },
  ),
```
另附上完整的代码
[line_demo_page.dart.zip](https://github.com/JDongKhan/flutter_chart/files/12210890/line_demo_page.dart.zip)

**Comment by JDongKhan** [comment]
@WeiKuang  你这样设置有什么问题吗？

**Comment by WeiKuang** [comment]
每次点击图表，线都会往后跑。

**Comment by JDongKhan** [comment]
这个每次点击会重新渲染数据，你看下是不是点击完修改了数据的x坐标值。

**Comment by JDongKhan** [comment]
```
 position: (item) {
       return i++;
 },
```
我看到代码里有对position不停的++

**Comment by JDongKhan** [comment]
还有可以通过 设置margin和padding调整chart的位置。
```
margin: const EdgeInsets.only(left: 30, top: 0, right: 10, bottom: 25),
padding: const EdgeInsets.only(left: 30, top: 0, right: 10, bottom: 0),
```

**Comment by WeiKuang** [comment]
谢谢解答，🙏

**Comment by JDongKhan** [comment]
有关第三个Feature，我在example写了个demo，可以去设置线的过渡色，但是这个好像得自己去计算，不确定是否能解决这个问题，麻烦你有时间研究下，如果你有更好的想法可以在这里留下你的思路。
![苏宁豆芽图片20230803152502946](https://github.com/JDongKhan/flutter_chart/assets/4929805/522f7c67-023d-4076-8d04-cd56f237196f)
