### ISSUE TITLE
[BUG] Y坐标 min max如果为负数，则Y轴的划线逻辑出错

### ISSUE THREAD

**Issue by jiyahan** [JDongKhan/flutter_chart#10]
**Describe the bug**
Y坐标 min max如果为负数，则Y轴的划线逻辑出错

**How to reproduce**
Y轴 坐标 min max设置为负数

**Screenshots (If contains)**
![1702372700567](https://github.com/JDongKhan/flutter_chart/assets/12442075/eb7b7587-27f5-4d95-aaa6-54b343d7473c)

**Comment by JDongKhan** [comment]
是指Y轴线下移了吗？

**Comment by jiyahan** [comment]
设置min：-100 max：100 Y轴的线只能划一半 就是划线这个逻辑有问题 ，只要数值出现负数就有问题

**Comment by JDongKhan** [comment]
@jiyahan  嗯，我已经修复了，你再试试还有问题吗？

**Comment by jiyahan** [comment]
试过了 可以了，谢谢大哥~~，方便问下 有考虑支持对数坐标轴吗？

**Comment by JDongKhan** [comment]
不好意思，暂无计划，最近工作比较忙，新功能比较耗时间。还有这种比较小众吧，如果可以自己画就行了。

**Comment by jiyahan** [comment]
好的 谢谢~~~
