### ISSUE TITLE
柱状图是否能监听点击事件

### ISSUE THREAD

**Issue by zbwCoder** [JDongKhan/flutter_chart#15]
比如我点击某一个柱子，怎么知道点击的这个柱子对应的数据

**Comment by JDongKhan** [comment]
ChartDimensionsCoordinateRender里添加了onClickChart方法，可以拿到信息，麻烦更新到0.3.4。

**Comment by zbwCoder** [comment]
> ChartDimensionsCoordinateRender里添加了onClickChart方法，可以获取信息，麻烦更新到0.3.4。

刚更新的啊，用上了，感谢感谢！
