### ISSUE TITLE
how to install this package?

### ISSUE THREAD

**Issue by WeiKuang** [JDongKhan/flutter_chart#2]
作者您好，插件如何引入工程，有考虑将其发布到pub.dev上吗？
再多嘴问一句，当Y轴设置最小值为5时，如果想在y=10处画条线，那么
```dart
LimitAnnotation(limit: 5),
```
感觉怪怪的，能否基于最小值为0计算呢。

**Comment by JDongKhan** [comment]
不好意思，建议你直接将工程clone到本地依赖吧。
我现在在中国，发布需要登录google账号，这个得翻墙。 前些年因发布过一些其他package搞过免费的vpn，现在好像不好弄了。 主要也不赚钱，也没必要为此买vpn。


关于后面的问题，多谢反馈，我自己的项目最小值都是0，所以画Annotation时没有减去最小值。 

我上传了一版，有时间可以更新下来试试。
