### ISSUE TITLE
annotation tooltip coincides with the charts line tooltip.

### ISSUE THREAD

**Issue by WeiKuang** [JDongKhan/flutter_chart#3]
I add funtion _drawTooltip in the image_annotation.dart
When image_annotation is clicked, the coincidence of Tooltip and line
what should i do，thank you.
![20230811142159](https://github.com/JDongKhan/flutter_chart/assets/12131724/4cde78bc-068c-48f5-95e8-690c9e19e78d)
![20230811142134](https://github.com/JDongKhan/flutter_chart/assets/12131724/b75922d2-ee37-4361-8be5-083b9bcbcd19)

**Comment by JDongKhan** [comment]
I have fixed it that only responds to the onTap of ImageAnnotation when clicking on ImageAnnotation.

**Comment by WeiKuang** [comment]
very nice!!
