### ISSUE TITLE
ImageAnnotation中，drawImage的图片模糊

### ISSUE THREAD

**Issue by WeiKuang** [JDongKhan/flutter_chart#4]
作者，您好。使用ImageAnnotation时，drawImage的图片很模糊。可否使用drawImageRect来替代？

**Comment by JDongKhan** [comment]
你加载图片的时候可以指定宽高的吧 或者 继承 Annotation自己实现一个自己的ImageAnnotation

**Comment by JDongKhan** [comment]
还有你的图片是否放到合适分辨率的目录下，我自己的项目就是放到了2x下面，理论图片合适不会出现模糊的。

**Comment by WeiKuang** [comment]
嗯，是的。你的做法是正确的
