### ISSUE TITLE
x轴起始点显示不全

### ISSUE THREAD

**Issue by WeiKuang** [JDongKhan/flutter_chart#5]
作者，您好。如图所示，x轴起始点显示不全。如果加上padding的话，整个图表也会向右移动。
![20230816164052](https://github.com/JDongKhan/flutter_chart/assets/12131724/063cc325-1a5b-4df5-9f0e-43d732be92f5)

**Comment by JDongKhan** [comment]
已经修复了

**Comment by WeiKuang** [comment]
nice person
