### ISSUE TITLE
tooltipWidgetRenderer太多，超出图表大小问题？

### ISSUE THREAD

**Issue by WeiKuang** [JDongKhan/flutter_chart#7]
作者，你好。请教个问题。当tooltipWidgetRenderer太多，超出图表范围时，会有裁剪，导致显示不全。如下图，请问这个如何解决？万分感谢。
<img width="196" alt="截屏2023-08-21 17 20 16" src="https://github.com/JDongKhan/flutter_chart/assets/12131724/48a39a19-d41d-457c-a2a0-dcc9a983cfd1">

**Comment by JDongKhan** [comment]
1、因Positioned定位时无法算出内容高度，所以tooltipWidgetRenderer返回的是PreferredSize组件，这个需要你自己提供size，便于组件做边界处理，你可以预估一个合理的高度。
2、内容不能超过chart组件，会被裁剪，如果超出可以让其内容滚动。

**Comment by JDongKhan** [comment]
如果你没有点击事件等需求，可以使用TextSpan处理所有内容，这个东西很容易计算宽高。

**Comment by WeiKuang** [comment]
感谢回复。
1、根据内容，计算得出的高度为600，但chart组件只有300，那给PreferredSize传递的高度是600还是300.我试着传了个600，但屏幕上没有显示任何widget.
2、set PreferredSize height == 300，让其内容滚动，但是手指接触屏幕时，tooltipWidgetRenderer已经消失。代码如下，是我写的不对么？
```dart
return PreferredSize(
    preferredSize: Size(130, 300),
    child: SingleChildScrollView(
      scrollDirection: Axis.vertical,
      child: Container(
        padding: const EdgeInsets.all(6),
        child: Column(
          children: [
          ],
        ),
      ),
    ),
  );
```

**Comment by JDongKhan** [comment]
PreferredSize 只是提供给使用者计算的，应该不会约束child，需要你给SingleChildScrollView套个sizebox。
比如
```
PreferredSize(
    preferredSize: const Size(60, 100),
    child: SizedBox(
      width: 60,
      height: 100,
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
          padding: const EdgeInsets.all(8),
          child: Text(text),
        ),
      ),
    ),
)

```

**Comment by JDongKhan** [comment]
还有手势的问题好像是外部识别区域写错了位置导致点击浮层也触发了，我修复一下。

**Comment by WeiKuang** [comment]
非常感谢，好人呐
