### ISSUE TITLE
[Feature] 希望能适配横向布局的柱状图

### ISSUE THREAD

**Issue by XiFengLang** [JDongKhan/flutter_chart#9]
**Version information**
 - Device: *e.g. iPhone X*
 - OS: *e.g. iOS 14.7.1*
 - Package Version: *e.g. v2.4.1*
 - Flutter Version: *e.g. v2.5.0*

**Is your feature request related to a problem?**
none

**Describe the solution you'd like**
BarChart 能适配横向布局
![image](https://github.com/JDongKhan/flutter_chart/assets/14857242/53de3e65-3e60-4316-8a05-b677b111a4b2)

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by XiFengLang** [comment]
对比了5个库，大佬你这个库接近我们的设计稿，图表也很多，希望能适配下横向布局的条形图

**Comment by JDongKhan** [comment]
嗯，好的，我抽个时间支持下。

**Comment by JDongKhan** [comment]
@XiFengLang  我已经搞了一版，先提交到main分支了，example跑了下没问题，只需要将ChartDimensionsCoordinateRender改为ChartInvertDimensionsCoordinateRender即可，如果你着急可以先试试。

**Comment by XiFengLang** [comment]
👍，我抽时间看看，现在用community_charts，踩了一堆坑。
